// Package manifests has the CRD manifests needed to bootstrap the operator
// the manifest files in this directory are autogenerated from the CRDs in
// this repository with
//
// ```
// controller-gen crd paths=./pkg/apis/etcd/v1beta2/... output:crd:artifacts:config=./manifests
// ```
package manifests

import "embed"

//go:embed *.yaml
var FS embed.FS
